/**
 * Questionnaire seed v1.1 — the questionnaire is data, not code
 * (CLAUDE.md architecture rule 3, SPEC.md §12).
 *
 * The Du-form `text` is taken verbatim from the Notion questionnaire v1.0
 * ("KI-Barometer – Fragebogen", May 2026); F6/F7 are the new v1.1 leadership
 * questions from SPEC.md §10. Widget/format annotations of the source
 * ("(Mehrfachauswahl)", "(Freitext, optional)", "— Skala 1 (…) – 10 (…)",
 * "____") are represented structurally via `type`/`options`, not in `text`.
 * `text_sie` changes ONLY the form of address, never the meaning.
 *
 * Choice `value`s are stable identifiers the Phase-2 KPI formulas depend on
 * (SPEC.md §10 — e.g. W1.1 adoption buckets, W2.1 class midpoints
 * 0 / 0.5 / 2 / 4 / 7.5 / 12). Never rename them.
 */

import type { Choice, Question, TemplateKey } from "@/lib/types";

/**
 * The nine real tools offered in O2 (excluding "other"/"none"). Reused as the
 * choice rows of W1.2; at runtime the rows are narrowed to
 * `profile.tools_used` via `condition.requires_tool` (SPEC.md §9).
 */
export const TOOL_CATALOG: Choice[] = [
  { value: "copilot365", label: "Microsoft Copilot 365" },
  { value: "chatgpt", label: "ChatGPT (OpenAI)" },
  { value: "claude", label: "Claude (Anthropic)" },
  { value: "gemini", label: "Google Gemini" },
  { value: "perplexity", label: "Perplexity" },
  { value: "github_copilot", label: "GitHub Copilot" },
  { value: "notion_ai", label: "Notion AI" },
  { value: "deepl_write", label: "DeepL Write" },
  { value: "internal_ai", label: "Eine unternehmensinterne KI-Lösung" },
];

export const QUESTIONS: Question[] = [
  // --- Onboarding (one-time baseline, ~3 min) ------------------------------
  {
    id: "q-o1",
    template_key: "onboarding",
    code: "O1",
    dimension: "meta",
    type: "single_choice",
    text: "Welcher Abteilung gehörst du an?",
    text_sie: "Welcher Abteilung gehören Sie an?",
    options: {
      kind: "choices",
      choices: [
        { value: "management", label: "Geschäftsleitung / Management" },
        { value: "sales", label: "Vertrieb / Sales" },
        { value: "marketing", label: "Marketing" },
        { value: "hr", label: "Personal / HR" },
        { value: "finance", label: "Finanzen / Controlling" },
        { value: "it", label: "IT / Technik" },
        { value: "operations", label: "Produktion / Operations" },
        { value: "support", label: "Kundenservice / Support" },
        { value: "rnd", label: "Forschung / Entwicklung" },
        { value: "other", label: "Andere" },
      ],
    },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 10,
    active: true,
  },
  {
    id: "q-o2",
    template_key: "onboarding",
    code: "O2",
    dimension: "tools",
    type: "multi_choice",
    text: "Welche KI-Tools nutzt du aktuell beruflich?",
    text_sie: "Welche KI-Tools nutzen Sie aktuell beruflich?",
    options: {
      kind: "choices",
      choices: [
        ...TOOL_CATALOG,
        { value: "other", label: "Andere:", allows_text: true },
        { value: "none", label: "Aktuell keine", exclusive: true },
      ],
    },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 20,
    active: true,
  },
  {
    id: "q-o3",
    template_key: "onboarding",
    code: "O3",
    dimension: "adoption",
    type: "single_choice",
    text: "Wie lange nutzt du KI-Tools schon beruflich?",
    text_sie: "Wie lange nutzen Sie KI-Tools schon beruflich?",
    options: {
      kind: "choices",
      choices: [
        { value: "lt_1m", label: "Weniger als 1 Monat" },
        { value: "1_3m", label: "1–3 Monate" },
        { value: "3_6m", label: "3–6 Monate" },
        { value: "6_12m", label: "6–12 Monate" },
        { value: "gt_1y", label: "Länger als 1 Jahr" },
        { value: "not_yet", label: "Noch gar nicht" },
      ],
    },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 30,
    active: true,
  },
  {
    id: "q-o4",
    template_key: "onboarding",
    code: "O4",
    dimension: "learning",
    type: "scale_1_10",
    text: "Wie schätzt du dein KI-Wissen ein?",
    text_sie: "Wie schätzen Sie Ihr KI-Wissen ein?",
    options: {
      kind: "scale",
      min: 1,
      max: 10,
      min_label: "Anfänger",
      max_label: "Experte",
    },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 40,
    active: true,
  },
  {
    id: "q-o5",
    template_key: "onboarding",
    code: "O5",
    dimension: "adoption",
    type: "multi_choice",
    text: "Wofür nutzt du KI hauptsächlich?",
    text_sie: "Wofür nutzen Sie KI hauptsächlich?",
    options: {
      kind: "choices",
      choices: [
        { value: "writing", label: "Texte schreiben & überarbeiten" },
        { value: "emails", label: "E-Mails formulieren" },
        { value: "research", label: "Recherche & Informationssuche" },
        { value: "summaries", label: "Zusammenfassungen erstellen" },
        { value: "translation", label: "Übersetzungen" },
        { value: "data_analysis", label: "Datenanalyse" },
        { value: "coding", label: "Programmierung / Coding" },
        { value: "brainstorming", label: "Brainstorming & Ideenfindung" },
        { value: "presentations", label: "Präsentationen erstellen" },
        { value: "images", label: "Bilder generieren" },
        { value: "meeting_notes", label: "Meeting-Protokolle" },
        { value: "other", label: "Andere:", allows_text: true },
      ],
    },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 50,
    active: true,
  },

  // --- Weekly pool (3–5 drawn per week, ~60 s, SPEC.md §9 rotation) --------
  {
    id: "q-w1.1",
    template_key: "weekly",
    code: "W1.1",
    dimension: "adoption",
    type: "single_choice",
    text: "Wie oft hast du diese Woche KI-Tools beruflich genutzt?",
    text_sie: "Wie oft haben Sie diese Woche KI-Tools beruflich genutzt?",
    options: {
      kind: "choices",
      choices: [
        { value: "none", label: "Gar nicht" },
        { value: "1_2", label: "1–2 mal" },
        { value: "3_5", label: "3–5 mal" },
        { value: "daily", label: "Täglich" },
        { value: "multiple_daily", label: "Mehrmals täglich" },
      ],
    },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 10,
    active: true,
  },
  {
    id: "q-w1.2",
    template_key: "weekly",
    code: "W1.2",
    dimension: "adoption",
    type: "single_choice",
    text: "Welches KI-Tool hast du diese Woche am häufigsten verwendet?",
    text_sie: "Welches KI-Tool haben Sie diese Woche am häufigsten verwendet?",
    options: {
      kind: "choices",
      choices: [...TOOL_CATALOG],
    },
    condition: { requires_tool: true },
    is_gap_pair_with: null,
    sort_order: 20,
    active: true,
  },
  {
    id: "q-w1.3",
    template_key: "weekly",
    code: "W1.3",
    dimension: "adoption",
    type: "single_choice",
    text: "Hast du diese Woche ein neues KI-Feature oder Tool ausprobiert?",
    text_sie: "Haben Sie diese Woche ein neues KI-Feature oder Tool ausprobiert?",
    options: {
      kind: "choices",
      choices: [
        { value: "yes", label: "Ja → Welches?", allows_text: true },
        { value: "no", label: "Nein" },
      ],
    },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 30,
    active: true,
  },
  {
    id: "q-w2.1",
    template_key: "weekly",
    code: "W2.1",
    dimension: "efficiency",
    type: "single_choice",
    text: "Wie viele Stunden hat dir KI diese Woche geschätzt gespart?",
    text_sie: "Wie viele Stunden hat Ihnen KI diese Woche geschätzt gespart?",
    options: {
      kind: "choices",
      // Class midpoints 0 / 0.5 / 2 / 4 / 7.5 / 12 (SPEC.md §10).
      choices: [
        { value: "none", label: "Keine" },
        { value: "lt_1", label: "Unter 1 Stunde" },
        { value: "1_3", label: "1–3 Stunden" },
        { value: "3_5", label: "3–5 Stunden" },
        { value: "5_10", label: "5–10 Stunden" },
        { value: "gt_10", label: "Mehr als 10 Stunden" },
      ],
    },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 40,
    active: true,
  },
  {
    id: "q-w2.2",
    template_key: "weekly",
    code: "W2.2",
    dimension: "efficiency",
    type: "text_optional",
    text: "Bei welcher Aufgabe war KI diese Woche besonders hilfreich?",
    text_sie: "Bei welcher Aufgabe war KI diese Woche besonders hilfreich?",
    options: null,
    condition: null,
    is_gap_pair_with: null,
    sort_order: 50,
    active: true,
  },
  {
    id: "q-w2.3",
    template_key: "weekly",
    code: "W2.3",
    dimension: "efficiency",
    type: "scale_1_10",
    text: "Wie würdest du die Qualität der KI-Outputs diese Woche bewerten?",
    text_sie: "Wie würden Sie die Qualität der KI-Outputs diese Woche bewerten?",
    options: {
      kind: "scale",
      min: 1,
      max: 10,
      min_label: "sehr schlecht",
      max_label: "exzellent",
    },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 60,
    active: true,
  },
  {
    id: "q-w3.1",
    template_key: "weekly",
    code: "W3.1",
    dimension: "trust",
    type: "single_choice",
    text: "Wie oft musstest du KI-Outputs diese Woche stark nacharbeiten?",
    text_sie: "Wie oft mussten Sie KI-Outputs diese Woche stark nacharbeiten?",
    options: {
      kind: "choices",
      // Inverted to 10 / 7.5 / 5 / 2.5 / 0 for the trust index (SPEC.md §10).
      choices: [
        { value: "never", label: "Nie" },
        { value: "rarely", label: "Selten" },
        { value: "sometimes", label: "Manchmal" },
        { value: "often", label: "Oft" },
        { value: "almost_always", label: "Fast immer" },
      ],
    },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 70,
    active: true,
  },
  {
    id: "q-w3.2",
    template_key: "weekly",
    code: "W3.2",
    dimension: "trust",
    type: "single_choice",
    text: "Hast du diese Woche eine fehlerhafte oder irreführende KI-Antwort erhalten?",
    text_sie:
      "Haben Sie diese Woche eine fehlerhafte oder irreführende KI-Antwort erhalten?",
    options: {
      kind: "choices",
      choices: [
        { value: "yes", label: "Ja → Bei welchem Tool?", allows_text: true },
        { value: "no", label: "Nein" },
        { value: "dont_know", label: "Weiß nicht" },
      ],
    },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 80,
    active: true,
  },
  {
    id: "q-w3.3",
    template_key: "weekly",
    code: "W3.3",
    dimension: "trust",
    type: "scale_1_10",
    text: "Wie sicher fühlst du dich im Umgang mit KI-Tools?",
    text_sie: "Wie sicher fühlen Sie sich im Umgang mit KI-Tools?",
    options: {
      kind: "scale",
      min: 1,
      max: 10,
      min_label: "sehr unsicher",
      max_label: "sehr sicher",
    },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 90,
    active: true,
  },
  {
    id: "q-w4.1",
    template_key: "weekly",
    code: "W4.1",
    dimension: "sentiment",
    type: "single_choice",
    text: "Wie empfindest du den Einsatz von KI in deinem Arbeitsalltag aktuell?",
    text_sie:
      "Wie empfinden Sie den Einsatz von KI in Ihrem Arbeitsalltag aktuell?",
    options: {
      kind: "choices",
      // Mapped to 10 / 7.5 / 5 / 2.5 / 0 for the sentiment index (SPEC.md §10).
      choices: [
        { value: "strong_relief", label: "Stark entlastend 😀" },
        { value: "some_relief", label: "Eher entlastend 🙂" },
        { value: "neutral", label: "Neutral 😐" },
        { value: "some_strain", label: "Eher belastend 😕" },
        { value: "strong_strain", label: "Stark belastend 😞" },
      ],
    },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 100,
    active: true,
  },
  {
    id: "q-w4.2",
    template_key: "weekly",
    code: "W4.2",
    dimension: "sentiment",
    type: "scale_1_10",
    text: "Wie ist deine Stimmung in Bezug auf KI im Unternehmen diese Woche?",
    text_sie:
      "Wie ist Ihre Stimmung in Bezug auf KI im Unternehmen diese Woche?",
    options: {
      kind: "scale",
      min: 1,
      max: 10,
      min_label: "sehr negativ",
      max_label: "sehr positiv",
    },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 110,
    active: true,
  },
  {
    id: "q-w4.3",
    template_key: "weekly",
    code: "W4.3",
    dimension: "sentiment",
    type: "text_optional",
    text: "Gibt es etwas, das dich diese Woche im Umgang mit KI gestört oder geärgert hat?",
    text_sie:
      "Gibt es etwas, das Sie diese Woche im Umgang mit KI gestört oder geärgert hat?",
    options: null,
    condition: null,
    is_gap_pair_with: null,
    sort_order: 120,
    active: true,
  },

  // --- Monthly (8–12 questions, 5–8 min) ------------------------------------
  {
    id: "q-m1.1",
    template_key: "monthly",
    code: "M1.1",
    dimension: "roi",
    type: "number",
    text: "Wie viele Stunden hat dir KI in diesem Monat insgesamt gespart?",
    text_sie: "Wie viele Stunden hat Ihnen KI in diesem Monat insgesamt gespart?",
    options: { kind: "number", unit: "Stunden", min: 0 },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 10,
    active: true,
  },
  {
    id: "q-m1.2",
    template_key: "monthly",
    code: "M1.2",
    dimension: "roi",
    type: "text_optional",
    text: "Welche Aufgabe würdest du ohne KI heute nicht mehr in der gleichen Zeit erledigen können?",
    text_sie:
      "Welche Aufgabe würden Sie ohne KI heute nicht mehr in der gleichen Zeit erledigen können?",
    options: null,
    condition: null,
    is_gap_pair_with: null,
    sort_order: 20,
    active: true,
  },
  {
    id: "q-m1.3",
    template_key: "monthly",
    code: "M1.3",
    dimension: "roi",
    type: "scale_minus5_plus5",
    text: "Wenn du an deinen Arbeitsalltag denkst: Wie hat sich deine Produktivität in diesem Monat durch KI verändert?",
    text_sie:
      "Wenn Sie an Ihren Arbeitsalltag denken: Wie hat sich Ihre Produktivität in diesem Monat durch KI verändert?",
    options: {
      kind: "scale",
      min: -5,
      max: 5,
      min_label: "deutlich verschlechtert",
      max_label: "deutlich verbessert",
    },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 30,
    active: true,
  },
  {
    id: "q-m1.4",
    template_key: "monthly",
    code: "M1.4",
    dimension: "roi",
    type: "text_optional",
    text: 'Welcher konkrete Erfolg / welches "Aha-Erlebnis" mit KI fällt dir aus diesem Monat ein?',
    text_sie:
      'Welcher konkrete Erfolg / welches "Aha-Erlebnis" mit KI fällt Ihnen aus diesem Monat ein?',
    options: null,
    condition: null,
    is_gap_pair_with: null,
    sort_order: 40,
    active: true,
  },
  {
    id: "q-m2.1",
    template_key: "monthly",
    code: "M2.1",
    dimension: "tools",
    type: "tool_matrix",
    text: "Bewerte die KI-Tools, die du nutzt, nach Nützlichkeit für deinen Arbeitsalltag:",
    text_sie:
      "Bewerten Sie die KI-Tools, die Sie nutzen, nach Nützlichkeit für Ihren Arbeitsalltag:",
    // Per tool: usefulness 1 (gar nicht nützlich) – 10 (unverzichtbar)
    // + uses per week; rows come from profile.tools_used (types.ts).
    options: { kind: "tool_matrix" },
    condition: { requires_tool: true },
    is_gap_pair_with: null,
    sort_order: 50,
    active: true,
  },
  {
    id: "q-m2.2",
    template_key: "monthly",
    code: "M2.2",
    dimension: "tools",
    type: "text_optional",
    text: "Welches Tool fehlt dir aktuell in deinem KI-Werkzeugkasten?",
    text_sie: "Welches Tool fehlt Ihnen aktuell in Ihrem KI-Werkzeugkasten?",
    options: null,
    condition: null,
    is_gap_pair_with: null,
    sort_order: 60,
    active: true,
  },
  {
    id: "q-m2.3",
    template_key: "monthly",
    code: "M2.3",
    dimension: "tools",
    type: "text_optional",
    text: "Welches Tool nutzt du kaum / gar nicht – und warum?",
    text_sie: "Welches Tool nutzen Sie kaum / gar nicht – und warum?",
    options: null,
    condition: null,
    is_gap_pair_with: null,
    sort_order: 70,
    active: true,
  },
  {
    id: "q-m3.1",
    template_key: "monthly",
    code: "M3.1",
    dimension: "learning",
    type: "scale_1_10",
    text: "Wie sicher fühlst du dich aktuell im Umgang mit KI insgesamt?",
    text_sie: "Wie sicher fühlen Sie sich aktuell im Umgang mit KI insgesamt?",
    options: {
      kind: "scale",
      min: 1,
      max: 10,
      min_label: "sehr unsicher",
      max_label: "sehr sicher",
    },
    condition: null,
    is_gap_pair_with: "F7",
    sort_order: 80,
    active: true,
  },
  {
    id: "q-m3.2",
    template_key: "monthly",
    code: "M3.2",
    dimension: "learning",
    type: "multi_choice",
    text: "In welchen Bereichen würdest du dir mehr Schulung / Weiterbildung wünschen?",
    text_sie:
      "In welchen Bereichen würden Sie sich mehr Schulung / Weiterbildung wünschen?",
    options: {
      kind: "choices",
      choices: [
        { value: "basics", label: "Grundlagen & Funktionsweise von KI" },
        {
          value: "prompt_engineering",
          label: "Prompt Engineering (gute Anweisungen formulieren)",
        },
        { value: "specific_tool", label: "Spezifisches Tool:", allows_text: true },
        { value: "data_analysis", label: "KI im Bereich Datenanalyse" },
        { value: "creative", label: "KI für kreative Aufgaben" },
        {
          value: "privacy_legal",
          label: "Datenschutz & rechtliche Rahmenbedingungen",
        },
        { value: "ethics", label: "KI-Ethik & verantwortungsvoller Einsatz" },
        { value: "automation", label: "Automatisierung & Workflows" },
        { value: "none", label: "Kein Bedarf", exclusive: true },
      ],
    },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 90,
    active: true,
  },
  {
    id: "q-m3.3",
    template_key: "monthly",
    code: "M3.3",
    dimension: "learning",
    type: "single_choice",
    text: "Hast du in diesem Monat einen KI-Kurs absolviert?",
    text_sie: "Haben Sie in diesem Monat einen KI-Kurs absolviert?",
    options: {
      kind: "choices",
      choices: [
        { value: "yes", label: "Ja → Welchen?", allows_text: true },
        { value: "no", label: "Nein" },
      ],
      followup_scale: { on_value: "yes", text: "Wie hilfreich war er?" },
    },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 100,
    active: true,
  },
  {
    id: "q-m4.1",
    template_key: "monthly",
    code: "M4.1",
    dimension: "culture",
    type: "scale_1_10",
    text: "Wie offen ist die Kultur in deinem Team gegenüber KI-Einsatz?",
    text_sie: "Wie offen ist die Kultur in Ihrem Team gegenüber KI-Einsatz?",
    options: {
      kind: "scale",
      min: 1,
      max: 10,
      min_label: "sehr verschlossen",
      max_label: "sehr offen",
    },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 110,
    active: true,
  },
  {
    id: "q-m4.2",
    template_key: "monthly",
    code: "M4.2",
    dimension: "culture",
    type: "single_choice",
    text: "Sprecht ihr im Team über eure KI-Erfahrungen?",
    text_sie: "Sprechen Sie im Team über Ihre KI-Erfahrungen?",
    options: {
      kind: "choices",
      choices: [
        { value: "regularly", label: "Ja, regelmäßig" },
        { value: "sometimes", label: "Manchmal" },
        { value: "rarely", label: "Selten" },
        { value: "never", label: "Nie" },
      ],
    },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 120,
    active: true,
  },
  {
    id: "q-m4.3",
    template_key: "monthly",
    code: "M4.3",
    dimension: "culture",
    type: "text_optional",
    text: "Welche Sorgen oder Bedenken hast du persönlich in Bezug auf KI im Unternehmen?",
    text_sie:
      "Welche Sorgen oder Bedenken haben Sie persönlich in Bezug auf KI im Unternehmen?",
    options: null,
    condition: null,
    is_gap_pair_with: null,
    sort_order: 130,
    active: true,
  },
  {
    id: "q-m4.4",
    template_key: "monthly",
    code: "M4.4",
    dimension: "culture",
    type: "text_optional",
    text: "Welche Chancen siehst du persönlich in Bezug auf KI im Unternehmen?",
    text_sie:
      "Welche Chancen sehen Sie persönlich in Bezug auf KI im Unternehmen?",
    options: null,
    condition: null,
    is_gap_pair_with: null,
    sort_order: 140,
    active: true,
  },
  {
    id: "q-m5.1",
    template_key: "monthly",
    code: "M5.1",
    dimension: "strategy",
    type: "scale_1_10",
    text: "Hast du das Gefühl, dass die Unternehmensleitung eine klare KI-Strategie verfolgt?",
    text_sie:
      "Haben Sie das Gefühl, dass die Unternehmensleitung eine klare KI-Strategie verfolgt?",
    options: {
      kind: "scale",
      min: 1,
      max: 10,
      min_label: "gar nicht",
      max_label: "sehr klar",
    },
    condition: null,
    is_gap_pair_with: "F6",
    sort_order: 150,
    active: true,
  },
  {
    id: "q-m5.2",
    template_key: "monthly",
    code: "M5.2",
    dimension: "strategy",
    type: "scale_1_10",
    text: "Werden dir Informationen, Updates und Schulungen rund um KI ausreichend zur Verfügung gestellt?",
    text_sie:
      "Werden Ihnen Informationen, Updates und Schulungen rund um KI ausreichend zur Verfügung gestellt?",
    options: {
      kind: "scale",
      min: 1,
      max: 10,
      min_label: "gar nicht ausreichend",
      max_label: "sehr ausreichend",
    },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 160,
    active: true,
  },
  {
    id: "q-m5.3",
    template_key: "monthly",
    code: "M5.3",
    dimension: "strategy",
    type: "text_optional",
    text: "Wenn du eine Sache an der KI-Einführung in eurem Unternehmen ändern könntest – was wäre das?",
    text_sie:
      "Wenn Sie eine Sache an der KI-Einführung in Ihrem Unternehmen ändern könnten – was wäre das?",
    options: null,
    condition: null,
    is_gap_pair_with: null,
    sort_order: 170,
    active: true,
  },
  {
    id: "q-m6.1",
    template_key: "monthly",
    code: "M6.1",
    dimension: "nps",
    type: "scale_0_10",
    text: "Wie wahrscheinlich ist es, dass du das von dir am meisten genutzte KI-Tool einer Kollegin oder einem Kollegen weiterempfehlen würdest?",
    text_sie:
      "Wie wahrscheinlich ist es, dass Sie das von Ihnen am meisten genutzte KI-Tool einer Kollegin oder einem Kollegen weiterempfehlen würden?",
    options: {
      kind: "scale",
      min: 0,
      max: 10,
      min_label: "gar nicht wahrscheinlich",
      max_label: "sehr wahrscheinlich",
    },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 180,
    active: true,
  },

  // --- Leadership (monthly, team_lead/org_admin only) -----------------------
  {
    id: "q-f1",
    template_key: "leadership",
    code: "F1",
    dimension: "roi",
    type: "currency",
    text: "Wie viel Budget habt ihr im aktuellen Monat für KI-Lizenzen ausgegeben?",
    text_sie:
      "Wie viel Budget haben Sie im aktuellen Monat für KI-Lizenzen ausgegeben?",
    options: { kind: "number", unit: "€", min: 0 },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 10,
    active: true,
  },
  {
    id: "q-f2",
    template_key: "leadership",
    code: "F2",
    dimension: "roi",
    type: "scale_1_10",
    text: "Wie schätzt du den Nutzen dieser Investition aktuell ein?",
    text_sie: "Wie schätzen Sie den Nutzen dieser Investition aktuell ein?",
    options: {
      kind: "scale",
      min: 1,
      max: 10,
      min_label: "kein Nutzen",
      max_label: "sehr hoher Nutzen",
    },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 20,
    active: true,
  },
  {
    id: "q-f3",
    template_key: "leadership",
    code: "F3",
    dimension: "roi",
    type: "text_optional",
    text: "Welche messbaren Erfolge durch KI siehst du in deinem Bereich?",
    text_sie: "Welche messbaren Erfolge durch KI sehen Sie in Ihrem Bereich?",
    options: null,
    condition: null,
    is_gap_pair_with: null,
    sort_order: 30,
    active: true,
  },
  {
    id: "q-f4",
    template_key: "leadership",
    code: "F4",
    dimension: "culture",
    type: "text_optional",
    text: "Welche Hindernisse beobachtest du bei der KI-Einführung in deinem Team?",
    text_sie:
      "Welche Hindernisse beobachten Sie bei der KI-Einführung in Ihrem Team?",
    options: null,
    condition: null,
    is_gap_pair_with: null,
    sort_order: 40,
    active: true,
  },
  {
    id: "q-f5",
    template_key: "leadership",
    code: "F5",
    dimension: "roi",
    type: "currency",
    text: "Wie hoch schätzt du den durchschnittlichen Stundensatz in deinem Team?",
    text_sie:
      "Wie hoch schätzen Sie den durchschnittlichen Stundensatz in Ihrem Team?",
    options: { kind: "number", unit: "€/Stunde", min: 0 },
    condition: null,
    is_gap_pair_with: null,
    sort_order: 50,
    active: true,
  },
  {
    id: "q-f6",
    template_key: "leadership",
    code: "F6",
    dimension: "strategy",
    type: "scale_1_10",
    text: "Wie klar ist eure KI-Strategie aus deiner Sicht im Unternehmen kommuniziert?",
    text_sie:
      "Wie klar ist Ihre KI-Strategie aus Ihrer Sicht im Unternehmen kommuniziert?",
    options: {
      kind: "scale",
      min: 1,
      max: 10,
      min_label: "gar nicht klar",
      max_label: "sehr klar",
    },
    condition: null,
    is_gap_pair_with: "M5.1",
    sort_order: 60,
    active: true,
  },
  {
    id: "q-f7",
    template_key: "leadership",
    code: "F7",
    dimension: "learning",
    type: "scale_1_10",
    text: "Wie schätzt du die KI-Kompetenz deines Teams insgesamt ein?",
    text_sie: "Wie schätzen Sie die KI-Kompetenz Ihres Teams insgesamt ein?",
    options: {
      kind: "scale",
      min: 1,
      max: 10,
      min_label: "sehr gering",
      max_label: "sehr hoch",
    },
    condition: null,
    is_gap_pair_with: "M3.1",
    sort_order: 70,
    active: true,
  },
];

/** The 12 weekly pool questions the rotation draws from (SPEC.md §9). */
export const WEEKLY_POOL: Question[] = QUESTIONS.filter(
  (question) => question.template_key === "weekly",
);

/** Active questions of a template, sorted by sort_order. */
export function questionsFor(template: TemplateKey): Question[] {
  return QUESTIONS.filter(
    (question) => question.template_key === template && question.active,
  ).sort((a, b) => a.sort_order - b.sort_order);
}
